export const authConstant = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    SIGNOUT_REQUEST: "SIGNOUT_REQUEST",
    SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
    SIGNOUT_FAILURE: 'SIGNOUT_FAILURE'
}

export const userConstants = {
    SINGUP_REQUEST: "SINGUP_REQUEST",
    SINGUP_SUCCESS: "SINGUP_SUCCESS",
    SIGNUP_FAILURE: "SINGUP_FAILURE"
}

export const catagoryConstants = {
    CATAGORY_LIST_REQUEST: 'CATAGORY_LIST_REQUEST',
    CATAGORY_LIST_SUCCESS: 'CATAGORY_LIST_SUCCESS',
    CATAGORY_LIST_FAILURE: 'CATAGORY_LIST_FAILURE',
    CREATE_CATAGORY_REQUEST: 'CREATE_CATAGORY_REQUEST',
    CREATE_CATAGORY_SUCCESS: 'CREATE_CATAGORY_SUCCESS',
    CREATE_CATAGORY_FAILURE: 'CREATE_CATAGORY_FAILURE',
    UPDATE_CATAGORY_REQUEST: 'UPDATE_CATAGORY_REQUEST',
    UPDATE_CATAGORY_SUCCESS: 'UPDATE_CATAGORY_SUCCESS',
    UPDATE_CATAGORY_FAILURE: 'UPDATE_CATAGORY_FAILURE',
    DELETE_CATAGORY_REQUEST: 'DELETE_CATAGORY_REQUEST',
    DELETE_CATAGORY_SUCCESS: 'DELETE_CATAGORY_SUCCESS',
    DELETE_CATAGORY_FAILURE: 'DELETE_CATAGORY_FAILURE',
}

export const productConstants = {
    CREATE_PRODUCT_REQUEST: 'CREATE_PRODUCT_REQUEST',
    CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAILURE: 'CREATE_PRODUCT_FAILURE',
    GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
}
export const pageConstants = {
    CREATE_PAGE_REQUEST: 'CREATE_PAGE_REQUEST',
    CREATE_PAGE_SUCCESS: 'CREATE_PAGE_SUCCESS',
    CREATE_PAGE_FAILURE: 'CREATE_PAGE_FAILURE'
}
export const orderConstants = {
    GET_ALL_ORDERS_REQUEST: 'GET_ALL_ORDERS_REQUEST',
    GET_ALL_ORDERS_SUCCESS: 'GET_ALL_ORDERS_SUCCESS',
    GET_ALL_ORDERS_FAILURE: 'GET_ALL_ORDERS_FAILURE',
}